### PR TITLE
Updated Russian translation and a very basic README file

### PR DESCRIPTION
**Pull request by prokoudine**
You might want a more verbose README file anyway, but that's a start :)

### CODE REVIEW

**Comment by prokoudine** [comment]
Um, if I resolve the conflict, will you merge it? :)

**Comment by thezbyg** [comment]
I am really sorry for 2 year delay before any response. Would you like to be added as Gpick collaborator to allow commit access without pull requests?

Could you update your translations from template at https://github.com/thezbyg/gpick/wiki/translation/template.pot ? And no, you do not have to resolve the README.md file conflict.

**Comment by prokoudine** [comment]
Albertas, it's perfectly OK :) I'll see if I can give the translation update a shot this weekend. Push access isn't all that necessary, I'm just a lurker.

**Comment by prokoudine** [comment]
Created a different PR with just the ru.po update and a question.

**Pull request closed without merging**
